### ISSUE TITLE
Describe is not defined

### ISSUE THREAD

**Issue by ali-master** [nadeesha/saul#23]
Hi,

When I want to start and watch the application for contributing, I receive an error with the following message:

```
var suite = exports.suite = describe; // eslint-disable-line no-undef

ReferenceError: describe is not defined
```

Would you please help me in solving this problem in development mode?

**Comment by nadeesha** [comment]
@ali-master I think you're facing the same issue as #4. 

Have you done the configuration mentioned here: https://github.com/nadeesha/saul#jest

**Comment by ali-master** [comment]
Hi again,

Thank you for replying to me.
The problem is still there and that is: I wanna run your written codes after I cloned the code, but it says the same problem I told you before.

Can you please tell me the installation and running guide for who wants to run the code base for contributing?
